version: 2.1

jobs:
  build:
    docker:
      - image: gcr.io/k8s-skaffold/skaffold:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USERNAME" --password-stdin "$REGISTRY_HOSTNAME"
      - run: skaffold build

workflows:
  build-workflow:
    jobs:
      - build:
          context: common